### ISSUE TITLE
:art: Angular Playground #1 | Create mock-up of Projects page  

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#1]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14251/angular-creating-an-angular-playground-and-understanding-components)

### Description
As a Product Owner, I want a mock-up of my Projects page, so that I know what the end result will look like.

### Tasks
Mock-up shows...
- [ ] Location of table
- [ ] Location of drop-down
- [ ] Location of search box
- [ ] Location of any titles, buttons, text, etc.

### Acceptance Criteria
- [ ] Mock-up approved by Product Owner
- [ ] Approved mock-up attached to PBI in a comment
