### ISSUE TITLE
:sparkles: Recipe App | Ingredients List | Add list to UI

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#10]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a user, I want a list of ingredients, so that I can see what choices I have when making recipes.

### Tasks
- [ ] Create list of mocked ingredients
- [ ] Display mocked ingredients on page

### Acceptance Criteria
- [ ] Ingredients shown on screen
- [ ] List matches mock-up
- [ ] Can access via `/ingredients` route
- [ ] Screenshot of page attached to PBI as comment
