### ISSUE TITLE
:sparkles: Recipe App | Ingredients List | Create API endpoint

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#11]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a Product Owner, I want my ingredients to come from an API, so they can be retrieved from a database.

### Tasks
- [ ] Create API endpoint `/Ingredients`
- [ ] Return the mock ingredients from the API
- [ ] Call the API from the Angular app

### Acceptance Criteria
- [ ] Mock ingredients deleted from Angular app
- [ ] Mock ingredients returned via API call
- [ ] UI remains unchanged
