### ISSUE TITLE
:sparkles: Recipe App | Ingredients List | Add Ingredients to database

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#12]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a Product Owner, I want my ingredients to be stored in a database, so I can add/edit/delete ingredients.

### Tasks
- [ ] Create Ingredients table
- [ ] Add the mock ingredients to table
- [ ] Return list of ingredients from the database

### Acceptance Criteria
- [ ] Ingredients table exists
- [ ] Ingredients added to the database
- [ ] `/Ingredients` endpoint returns data from database
