### ISSUE TITLE
:sparkles: Angular Playground #2 | Create Projects table

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#2]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14251/angular-creating-an-angular-playground-and-understanding-components)

### Description
As a user, I want to see a table of projects, so that I have all the projects' information visible to me.

### Tasks
- [ ] Create `ProjectsList` component
- [ ] Add project data to `ProjectList` component
- [ ] Display project data in a table

### Acceptance Criteria
- [ ] `ProjectList` component contains project data
- [ ] All project data is displayed in the table
- [ ] Table matches mock-up
- [ ] Screenshot of page attached to PBI as comment
