### ISSUE TITLE
:sparkles: Recipe App | Ingredients List | Add search functionality

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#24]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a User, I want to search for ingredients, so that I can find specific ingredients easily.

### Tasks
- [ ] Wire up searchbox to API
- [ ] API returns filtered results

### Acceptance Criteria
- [ ] Can enter text into the search box
- [ ] Ingredients list shows ingredients whose name contains the search text
- [ ] Search filters ingredients in real-time
