### ISSUE TITLE
:art: Recipe App | Recipe List | UI Mock-up

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#25]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a Product Owner, I want to see what my recipe list page will look like, so that I can agree to build.

### Tasks
- [ ] Show list of recipes
- [ ] Show searchbox
- [ ] Show Add New Recipe button

### Acceptance Criteria
- [ ] Mock-up approved by Product Owner
- [ ] Mock-up attached to PBI as a comment
