### ISSUE TITLE
:sparkles: Recipe App | Recipe List | Add search functionality

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#26]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a User, I want to search for recipes, so that I can find specific recipes easily.

### Tasks
- [ ] Wire up searchbox to API
- [ ] API returns filtered results

### Acceptance Criteria
- [ ] Can enter text into the search box
- [ ] Recipe list shows recipes whose name contains the search text
- [ ] Search filters recipes in real-time
