### ISSUE TITLE
:sparkles: Recipe App | Recipe List | Add list to UI

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#27]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a user, I want a list of recipes, so that I can choose something to cook.

### Tasks
- [ ] Create list of mocked recipes
- [ ] Display mocked recipes on page

### Acceptance Criteria
- [ ] Recipes shown on screen
- [ ] List matches mock-up
- [ ] Can access via `/recipes` route
- [ ] When navigating to the homepage (ie `/`), it redirects to `/recipes`
- [ ] Screenshot of page attached to PBI as comment
