### ISSUE TITLE
:sparkles: Recipe App | Recipe List | Create API endpoint

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#28]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a Product Owner, I want my recipes to come from an API, so they can be retrieved from a database.

### Tasks
- [ ] Create API endpoint `/recipes`
- [ ] Return the mock recipes from the API
- [ ] Call the API from the Angular app

### Acceptance Criteria
- [ ] Mock recipes deleted from Angular app
- [ ] Mock recipes returned via API call
- [ ] UI remains unchanged
