### ISSUE TITLE
:sparkles: Recipe App | Recipe List | Add recipes to database

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#29]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a Product Owner, I want my recipes to be stored in a database, so I can add/edit/delete recipes.

### Tasks
- [ ] Create Recipes table
- [ ] Add the mock recipes to table
- [ ] Create a stored procedure that returns all recipes from the database
- [ ] Return list of recipes from the database by calling the stored procedure

### Acceptance Criteria
- [ ] Recipes table exists
- [ ] Recipes added to the database
- [ ] `/Recipes` endpoint returns data from database
