### ISSUE TITLE
:sparkles: Angular Playground #3 | Show Alert when project is clicked

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#3]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14251/angular-creating-an-angular-playground-and-understanding-components)

### Description
As a user, I want to open a Javascript Alert when I click on a project, so that I can show more info later on.

### Tasks
- [ ] Wire up the `(click)` event on the table row
- [ ] Open a Javascript Alert when a row is clicked
- [ ] Show the name of the project in the Alert

### Acceptance Criteria
- [ ] Alert appears when table row is clicked
- [ ] Alert shows the clicked project's name
