### ISSUE TITLE
:brain: Spike | Learn about SQL Stored Procedures

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#36]
# Description
As a developer, I want to learn the basics of stored procedures, so that I can use them correctly in my applications.

# Tasks
- [ ] Read the [stored procedures article](https://learn.microsoft.com/en-us/sql/relational-databases/stored-procedures/stored-procedures-database-engine?view=sql-server-ver16)
- [ ] Learn how to [use stored procedures in EF Core](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries)
- [ ] Learn how to add/remove stored procedures to/from the database using [code-first migrations](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#arbitrary-changes-via-raw-sql)
- [ ] Create a stored procedure to **add a new ingredient** to the recipe database

# Acceptance Criteria
- [ ] `create_ingredient` stored proc created
- [ ] stored proc added to the database via code-first migrations
- [ ] API endpoint `/ingredients/add` uses stored proc to add ingredient to the database
