### ISSUE TITLE
:sparkles: Recipe App | Ingredients | Create delete endpoint

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#37]
# Description
As a user, I want to be able to delete unused ingredients, so I can keep my overall list useful.

# Tasks
- [ ] Create `/ingredients/delete/{id}` endpoint
- [ ] Create a `delete_ingredient` stored proc

# Acceptance Criteria
- [ ] Endpoint exists on correct address
- [ ] Endpoint uses stored proc to perform delete
- [ ] Stored proc only allows ingredient to be deleted if it's not used in a recipe
- [ ] Standard 2XX/4XX response codes
