### ISSUE TITLE
:recycle: Angular Playground #4 | Refactor ProjectList into presentation component

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#4]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14251/angular-creating-an-angular-playground-and-understanding-components)

### Pain
I want to use the `ProjectList` component in another page, for a different list of projects. Right now, the component can only show the original list of projects 😭

### Suggested Improvement
* Turn the `ProjectList` component into a Presentational Component.
* Change the project data to be passed in from the parent.
* Change the click event to be passed out to the parent.

### Tasks
- [ ] Move the project data out of the `ProjectList` component
- [ ] Use `@Input` to give the component the project data
- [ ] Use `@Output` to send the click event out

### Acceptance Criteria
- [ ] UI remains the same
- [ ] Click functionality remains the same
- [ ] `ProjectList` component can be reused on another page, with another list of projects.
