### ISSUE TITLE
:sparkles: Angular Playground #5 | Add project type dropdown filter

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#5]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14251/angular-creating-an-angular-playground-and-understanding-components)

### Description
As a user, I want to be able to filter on my list of projects, so that I only see projects of a given category.

The category information I want in my dropdown is:
| Project Type   | Description                              | IsArchived | Created Date | Created By      | Updated Date | Updated By      |
| -------------- | ---------------------------------------- | ---------- | ------------ | --------------- | ------------ | --------------- |
| Website        | Making awesome websites                  | FALSE      | 11/07/2012   | Jane Doe        | 11/09/2018   | John Doe        |
| Mobile         | Creating apps for Android and IOS        | FALSE      | 28/02/2009   | Jane Doe        | 10/04/2021   | Jane Doe        |
| Power Platform | Fast and cheap business ready apps       | FALSE      | 11/04/2017   | John Doe        | 12/02/2019   | Eliza Northwind |
| Data           | Apps about reporting and data processing | FALSE      | 20/01/2010   | Bob Northwind   | 14/12/2021   | Bob Northwind   |
| Games          | Games dev                                | TRUE       | 19/09/2020   | Eliza Northwind | 17/09/2022   | Bob Northwind   |

### Tasks
- [ ] Add project category data
- [ ] Display categories in dropdown
- [ ] Filter displayed projects based off selected category

### Acceptance Criteria
- [ ] Table data respects selected option in dropdown
- [ ] Screenshot of functionality attached to PBI as comment
