### ISSUE TITLE
:recycle: Angular Playground #6 | Refactor data into Services

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#6]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14253/angular-mocking-your-data-and-dependency-injection)

### Description
We need to refactor our project data and dropdown data to come from a service, in preparation for the back-end team to give us access to their APIs.

### Tasks
- [ ] Get project data from `ProjectsService`
- [ ] Get dropdown data from `ProjectCategoryService`

### Acceptance Criteria
- [ ] Data comes from respective services
- [ ] UI remains unchanged
- [ ] Functionality remains unchanged
