### ISSUE TITLE
:sparkles: Angular Playground #7 | Add search functionality

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#7]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14300/angular-observables)

### Description
As a user, I want to be able to search my list of projects, so that I can find projects with specific text in their name or description.

### Tasks
- [ ] Add searchbox to UI
- [ ] Wire up search to filter projects shown on the table
- [ ] Filter projects where the name **or** description contains the search text

### Acceptance Criteria
- [ ] Searchbox on UI
- [ ] App filters project based on search text
- [ ] Search behaviour works in real-time (as a user types into the searchbox)
