### ISSUE TITLE
:lipstick: Angular Playground #8 | Add Bootstrap styling to project

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#8]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14252/angular-styling-your-component)

### Description
As a Product Owner, I want a website that uses modern styling and responsiveness, so that the app looks good and works across multiple devices.

### Tasks
- [ ] Add `ng-bootstrap` to project
- [ ] Add Bootstrap grid system (containers, rows, cols, etc.)
- [ ] Add Bootstrap table styles to projects table
- [ ] Add Bootstrap form styles to inputs (dropdown, search)
- [ ] Add icon to header

### Acceptance Criteria
- [ ] Document icon added to header
- [ ] Form controls uses Bootstrap classes
- [ ] Table uses Bootstrap classes and SSW colours
- [ ] App is useable on desktop and mobile devices
- [ ] Screenshot of app attached to PBI as comment
- [ ] Done Video demoing project attached to PBI as comment
