### ISSUE TITLE
:art: Recipe App | Ingredients List | Mock-up

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.FireBootCamp.Backlog#9]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14244/angular-building-a-recipe-app)

### Description
As a Product Owner, I want an idea of how my Ingredients List page will look, so that we gain a shared understanding of what will be built.

### Tasks
- [ ] List of ingredients shown
- [ ] Buttons shown
- [ ] Searchbox shown

### Acceptance Criteria
- [ ] Mock-up approved by PO
- [ ] Approved mock-up attached to PBI as comment
